#!/bin/sh
MSP_PORT=/dev/ttyS2
MSP_BAUD=115200
MSP_FPS=20
MSP_SIZE=1280x720

case "$1" in
    start)
        [ -x /usr/bin/msposd ] || exit 0
        [ -e "$MSP_PORT" ] || exit 0
        killall -q msposd 2>/dev/null
        echo "Starting MSP DisplayPort OSD on $MSP_PORT @ ${MSP_BAUD}..."
        /usr/bin/msposd             --master "$MSP_PORT"             --baudrate "$MSP_BAUD"             --osd             -r "$MSP_FPS"             --ahi 1             -x 0             -z "$MSP_SIZE"             > /tmp/msposd.log 2>&1 &
        ;;
    stop)
        killall -q msposd
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
